
fragment ProjectFields on Project {
    id
    name
    startDate
    targetDate
    description
    icon
    color
    url
    status {
        name
    }
    projectUpdates {
        nodes {
            body
            createdAt
            user {
                name
            }
        }
    }
    teams {
        nodes {
            key
            name
        }
    }
    lead {
        name
        email
        avatarUrl
    }
    health
}


query GetProjects($endCursor: String) {
    projects(
        filter: {
            or: [
                {
                    status: {
                        name: { eq: "In Progress" }
                    }
                }
                {
                    and: [
                        { status: { name: { eq: "Completed" } } }
                        { completedAt: { gte: "-P7D" } }
                    ]
                }
            ]
        }
        first: 50
        after: $endCursor
    ) {
        pageInfo {
            hasNextPage
            endCursor
        }
        nodes {
            ...ProjectFields
        }
    }
}


query GetProject($id: String!) {
    project(id: $id) {
        ...ProjectFields
    }
}
