name: Deploy to ETHGlobal

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Copy .clasprc.ethglobal.json to ~/.clasprc.json
        run: cp .clasprc.ethglobal.json ~/.clasprc.json

      - name: Copy .clasp.ethglobal.json to target directory
        run: cp .clasp.ethglobal.json ../allhands/.clasp.json

      - name: Change directory to target and deploy with clasp
        run: |
          cd ../allhands
          npx clasp push
